name: 'Build and Push Docker Image'
description: 'Builds and pushes a Docker image to a container registry'
inputs:
  tag:
    description: 'The tag for the Docker image'
    required: true


runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Build and Push Docker Image
      run: |
        echo "Building Docker image with tag: ${{ inputs.tag }}"
        docker build -t plopez/app-plopez:${{ inputs.tag }} aplicativo/aplicativoNuevo/.
        docker tag plopez/app-plopez:${{ inputs.tag }} acrplopezfp2.azurecr.io/app-plopez:${{ inputs.tag }}
        az acr login --name acrplopezfp2
        docker push acrplopezfp2.azurecr.io/app-plopez:${{ inputs.tag }}
      shell: bash
    
