name: 'Build and Push Docker Image'
description: 'Builds and pushes a Docker image to a container registry'
inputs:
  version:
    description: 'The version for the Docker image'
    required: true
outputs:
  repository:
    description: 'The name of the ACR repository'
    value: ${{ steps.repo.outputs.repo_name }}


runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Determine Docker Repository
      id: repo
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "repo_name=app-plopez" >> $GITHUB_ENV
        elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
          echo "repo_name=releases" >> $GITHUB_ENV
        else
          echo "Unsupported branch: ${{ github.ref }}"
          exit 1
        fi
        echo "::set-output name=repository::${repo_name}"
      shell: bash
    
    - name: Build and Push Docker Image
      run: |
        echo "Building Docker image with version: ${{ inputs.version }} in repository ${{ env.repo_name }} "
        docker build -t plopez/${{ env.repo_name }}:${{ inputs.version }} aplicativo/aplicativoNuevo/.
        docker tag plopez/${{ env.repo_name }}:${{ inputs.version }} acrplopezfp2.azurecr.io/${{ env.repo_name }}:${{ inputs.version }}
        az acr login --name acrplopezfp2
        docker push acrplopezfp2.azurecr.io/${{ env.repo_name }}:${{ inputs.version }}
      shell: bash
    
