name: 'Build and Push Docker Image'
description: 'Builds and pushes a Docker image to a container registry'
inputs:
  version:
    description: 'The version for the Docker image'
    required: true
  branch:
    description: 'The branch name'
    required: true
outputs:
  repository:
    description: 'The name of the ACR repository'
    value: ${{ steps.repo.outputs.repository }}


runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Determine Docker Repository
      id: repo
      run: |
        if [ "${{ inputs.branch }}" == "main" ]; then
          REPOSITORY=releases
        elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
          REPOSITORY=develop
        else
          echo "Unsupported branch: ${{ inputs.branch }}"
          exit 1
        fi
        echo "REPOSITORY=${REPOSITORY}" >> $GITHUB_ENV
        echo "::set-output name=repository::${REPOSITORY}"
      shell: bash

    - name: Build and Push Docker Image
      run: |
        echo "Building Docker image with version: ${{ inputs.version }} in repository ${{ env.REPOSITORY }} "
        docker build -t plopez/${{ env.REPOSITORY }}:${{ inputs.version }} aplicativo/aplicativoNuevo/.
        docker tag plopez/${{ env.REPOSITORY }}:${{ inputs.version }} acrplopezfp2.azurecr.io/${{ env.REPOSITORY }}:${{ inputs.version }}
        az acr login --name acrplopezfp2
        docker push acrplopezfp2.azurecr.io/${{ env.REPOSITORY }}:${{ inputs.version }}
      shell: bash

    - name: Print Repository in Custom Action
      run: echo "The repository is ${{ steps.repo.outputs.repository }}"
      shell: bash
    
