name: 'Build and Push Docker Image'
description: 'Builds and pushes a Docker image to a container registry'
inputs:
  tag:
    description: 'The tag for the Docker image'
    required: true
  version:
    description: 'The version of the application'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Build and Push Docker Image
      run: |
        echo "Building Docker image with tag: ${{ inputs.version }}"
        docker build -t plopez/app-plopez:${{ inputs.version }} aplicativo/aplicativoNuevo/.
        docker tag plopez/app-plopez:${{ inputs.version }} acrplopezfp2.azurecr.io/app-plopez:${{ inputs.version }}
        az acr login --name acrplopezfp2
        docker push acrplopezfp2.azurecr.io/app-plopez:${{ inputs.version }}
        echo "::set-output name=image_url::acrplopezfp2.azurecr.io/app-plopez:${{ inputs.version }}"
      shell: bash
    