version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: concierto
    ports:
      - "3307:3306"  # Exposing MySQL on port 3307 to avoid conflicts
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: php_container
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
