name: Get Version from composer.json
description: Extract version from composer.json
runs:
  using: "composite"
  steps:
    - name: Extract Version
      id: extract_version
      run: |
        sudo apt-get update && sudo apt-get install -y jq
        VERSION=$(jq -r '.version' aplicativo/aplicativoNuevo/composer.json)
        if [ -z "$VERSION" ]; then
          echo "No se pudo obtener la versión desde composer.json"
          exit 1
        fi
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
      shell: bash
outputs:
  version:
    description: "The version extracted from composer.json"
    value: ${{ steps.extract_version.outputs.VERSION }}
