apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proyectofinal-ingress
  namespace: ns-plopez
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: proyectofinalplopez.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: proyectofinal-service
            port:
              number: 80