name: Execute Ansible Playbook

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute Ansible Playbook
      run: |
        cd ansible
        ansible-playbook -i inventaario playbook.yaml
