name: Execute Kubectl apply

on:
  workflow_dispatch:

jobs:
  k8s:
    name: 'Azure Kubernetes Service Deployment'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Install kubelogin
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        brew install Azure/kubelogin/kubelogin

    - name: Connection to cluster
      run: |
        az account set --subscription 86f76907-b9d5-46fa-a39d-aff8432a1868
        az aks get-credentials --resource-group ${{ vars.RESOURCE_GROUP_NAME }} --name ${{ vars.KUBERNETES_CLUSTER_NAME }} --overwrite-existing
        kubelogin convert-kubeconfig -l azurecli

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy
      run: |
        kubectl apply -f kubernetes/. -n ns-plopez
        # kubectl describe svc proyectofinal-service 
