name: Execute Kubectl apply

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main

jobs:
  k8s:
    name: 'Azure Kubernetes Service Deployment'
    runs-on: ubuntu-latest
    environment: production
 
    defaults:
      run:
        shell: bash

    steps:
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Connection to cluster
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.bashrc
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        sudo apt-get install build-essential
        brew install Azure/kubelogin/kubelogin
        kubelogin convert-kubeconfig -l azurecli
        az acr login --name ${{ vars.CONTAINER_REGISTRY_NAME }}
        az aks get-credentials --resource-group ${{ vars.RESOURCE_GROUP_NAME }} --name ${{ vars.KUBERNETES_CLUSTER_NAME }}

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy
      run: |
        kubectl apply -f kubernetes/.
        kubectl describe svc proyectofinal-service 
