name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Docker Image
        run: |
          docker build -t plopez/app-plopez:${{ inputs.tag }} aplicativo/aplicativoNuevo/.
          docker tag plopez/app-plopez:${{ inputs.tag }} acrplopezfp2.azurecr.io/app-plopez:${{ inputs.tag }}
          az acr login --name acrplopezfp2
          docker push acrplopezfp2.azurecr.io/app-plopez:${{ inputs.tag }}
