name: Docker Image CI Dev

on: 
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'aplicativo/aplicativoNuevo/**'
    
jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push-docker.yml
    with:
      tag: ${{ github.sha }}
