name: 4 . Docker Image CI Dev

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'aplicativo/aplicativoNuevo/**'

jobs:
  extract_version:
    uses: ./.github/workflows/get-version.yml
    with:
      branch: develop

  build_and_push:
    needs: extract_version
    uses: ./.github/workflows/build-and-push-docker.yml
    with:
      tag: ${{ needs.extract_version.outputs.version }}

