name: 5. Docker Image CI Pre/prod

on: 
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches: 
      - main
    paths:
      - 'aplicativo/aplicativoNuevo/**'
  push:
    branches:
      - develop

jobs:
  extract_version:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Version
        id: get_version
        run: |
          if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            VERSION=$(date +'%Y%m%d%H%M%S')
          else
            sudo apt-get update && sudo apt-get install -y jq
            version=$(jq -r '.version' aplicativo/aplicativoNuevo/composer.json) >> $GITHUB_OUTPUT
            if [ -z "$version" ]; then
              echo "No se pudo obtener la versión desde composer.json"
              exit 1
            fi
          fi
        shell: bash
      
      - name: Print version
        run: echo "Version is ${{ steps.get_version.outputs.version }}"

  build_and_push:
    needs: extract_version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Print version input
        run: echo "Version input is ${{ needs.extraact_version.outputs.tag }}"

      - name: Build and Push Docker Image
        uses: ./.github/actions/build-and-push-docker
        with:
          version: ${{ needs.extract_version.outputs.tag }}
