name: Docker Image CI Pre/prod

on: 
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches: 
      - main
    paths:
      - 'aplicativo/aplicativoNuevo/**'
    
jobs:
  extract-version:
    uses: ./.github/actions/get-versions

  build-and-push:
    needs: extract-version
    uses: ./.github/workflows/build-and-push-docker.yml
    with:
      tag: ${{ jobs.extract-version.outputs.version }}
