name: 5. Docker Image CI Pre/prod

on: 
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches: 
      - main
    paths:
      - 'aplicativo/aplicativoNuevo/**'
  push:
    branches:
      - develop

jobs:
  
  extract_version:
    uses: ./.github/workflows/get-version.yml
    with:
      branch: main

  debug_extracted_version:
    needs: extract_version
    runs-on: ubuntu-latest
    steps:
      - name: Check Extracted Version
        run: echo "Extracted VERSION:${{ needs.extract_version.outputs.version }}"
        shell: bash

  build_and_push:
    needs: [extract_version, debug_extracted_version]
    secrets: inherit
    uses: ./.github/workflows/build-and-push-docker.yml
    with:
      tag: ${{ needs.extract_version.outputs.version }}
