name: 5. Docker Image CI Pre/prod

on: 
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches: 
      - main
    paths:
      - 'aplicativo/aplicativoNuevo/**'
  push:
    branches:
      - develop

jobs:
  extract_tag:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.get_version.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Tag
        id: get_tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            tag=$(date +'%Y%m%d%H%M%S')
          else
            sudo apt-get update && sudo apt-get install -y jq
            tag=$(jq -r '.version' aplicativo/aplicativoNuevo/composer.json) >> $GITHUB_OUTPUT
            if [ -z "$tag" ]; then
              echo "No se pudo obtener la versión desde composer.json"
              exit 1
            fi
          fi
        shell: bash
      
      - name: Print tag
        run: echo "Tag is ${{ steps.get_version.outputs.tag }}"

  build_and_push:
    needs: extract_tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Print tag input
        run: echo "Tag input is ${{ needs.extract_tag.outputs.tag }}"

      - name: Build and Push Docker Image
        uses: ./.github/actions/build-and-push-docker
        with:
          version: ${{ needs.extract_tag.outputs.tag }}
