name: 5. Docker Image CI Pre/prod

on: 
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches: 
      - main
    paths:
      - 'aplicativo/aplicativoNuevo/**'
  push:
    branches:
      - develop

jobs:
  extract_version:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Version
        id: get_version
        uses: ./.github/actions/get-version
        with:
          branch: ${{ github.ref == 'refs/heads/develop' && 'develop' || 'main' }}
      
      - name: Print Version
        run: echo "La version guaardada es ${{ steps.get_version.outputs.version }}"
  
  print_version:
    needs: extract_version
    runs-on: ubuntu-latest
    steps:
      - name: Print extracted version
        run: echo "La version extraída es ${{ needs.extract_version.outputs.version }}"

  # build_and_push:
  #   needs: extract_version
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
      
  #     - name: Login to Azure
  #       uses: azure/login@v2
  #       with:
  #         creds: ${{ secrets.AZURE_CREDENTIALS }}
      
  #     - name: Print tag input
  #       run: echo "Tag input is ${{ needs.extract_tag.outputs.tag }}"

  #     - name: Build and Push Docker Image
  #       uses: ./.github/actions/build-and-push-docker
  #       with:
  #         version: ${{ needs.extract_tag.outputs.tag }}
