name: 5. Docker Image CI Pre/prod

on: 
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches: 
      - main
    paths:
      - 'aplicativo/aplicativoNuevo/**'
  push:
    branches:
      - develop

jobs:
  extract_version:
    uses: ./.github/workflows/get-version.yml
    with:
      branch: main

  build_and_push:
    needs: extract_version
    uses: ./.github/workflows/build-and-push-docker.yml
    with:
      tag: ${{ needs.extract_version.outputs.version }}
