name: 5. Docker Image CI Pre/prod

on: 
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches: 
      - main
    paths:
      - 'aplicativo/aplicativoNuevo/**'
  push:
    branches:
      - develop

jobs:
  
  extract_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Version
        id: get_version
        uses: ./.github/actions/get-version
        with:
          branch: ${{ github.ref == 'refs/heads/develop' && 'develop' || 'main' }}

      - name: Check Extracted Version
        run: |
          echo "Extracted VERSION (Main Workflow): ${{ steps.get_version.outputs.version }}"
        shell: bash

  build_and_push:
    needs: extract_version
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        uses: ./.github/actions/build-and-push-docker
        with:
          version: ${{ needs.extract_version.outputs.version }}
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
