name: 5. Docker Image CI Pre/prod

on: 
  workflow_dispatch:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

    outputs:
      version:
        description: 'Version of the image'
        value: ${{ jobs.extract_version.outputs.version }}
      repository:
        description: 'Repository of the image'
        value: ${{ jobs.build_and_push.outputs.repository }}
 

jobs:
  extract_version:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.get_version.outputs.version }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Version
        id: get_version
        uses: ./.github/actions/get-version
        with:
          branch: ${{ inputs.branch }}

      - name: Print version input (extract version)
        run: echo "La version que se va a taggear es ${{ steps.get_version.outputs.version }}"
  
  build_and_push:
    needs: extract_version
    runs-on: ubuntu-latest
    
    outputs:
      repository: ${{ steps.build_and_push.outputs.repository }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Build and Push Docker Image
        id: build_and_push
        uses: ./.github/actions/build-and-push-docker
        with:
          version: ${{ needs.extract_version.outputs.version }}
          branch: ${{ inputs.branch }}

        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }} 

  resolution_of_outputs:
    needs: [extract_version, build_and_push]
    runs-on: ubuntu-latest

    steps:
      - name: Print version output (build and push)
        run: echo "La version que se va a taggear es ${{ needs.extract_version.outputs.version }}"
      
      - name: Print repository output (build and push)
        run: echo "El repositorio de la imagen es ${{ needs.build_and_push.outputs.repository }}" 
