name: Docker Image CI

on: 
  #ci
  workflow_dispatch:
  pull_request:
    types:
    - opened
    branches: 
    - main
    paths:
    - 'aplicativo/aplicativoNuevo/**'
  #    - 'kubernetes/**'
    
jobs:
  build:
    name: 'Build and Push to ACR'
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.get_version.outputs.version }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Extract Version from docker-compose.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' aplicativo/aplicativoNuevo/docker-compose.json)
          if [ -z "$VERSION" ]; then
            echo "No se pudo obtener la versión desde docker-compose.json"
            exit 1
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: build and push
        run: |
          docker build -t plopez/app-plopez:1.0 aplicativo/aplicativoNuevo/.
          docker tag plopez/app-plopez:${{ env.VERSION }}  acrplopezfp2.azurecr.io/app-plopez:${{ env.VERSION }}
          az acr login --name acrplopezfp2
          docker push acrplopezfp2.azurecr.io/app-plopez:${{ env.VERSION }}
