name: Docker Image CI

on: 
  #ci
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'aplicativo/aplicativoNuevo/**'
    
jobs:
  build:
    name: 'Build and Push to ACR'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          

      - name: Set Docker Tag
        id: set_tag
        run: |
          TAG=$(date +'%Y%m%d%H%M%S')
          echo "TAG=${TAG}" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          docker build -t plopez/app-plopez:${{ env.TAG }} aplicativo/aplicativoNuevo/.
          docker tag plopez/app-plopez:${{ env.TAG }} acrplopezfp2.azurecr.io/app-plopez:${{ env.TAG }}
          az acr login --name acrplopezfp2
          docker push acrplopezfp2.azurecr.io/app-plopez:${{ env.TAG }}
