name: Get Version

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  extract_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Version
        id: set_version
        run: |
          if [ "${{ inputs.branch }}" == "develop" ]; then
            VERSION=$(date +'%Y%m%d%H%M%S')
          else
            sudo apt-get update && sudo apt-get install -y jq
            VERSION=$(jq -r '.version' aplicativo/aplicativoNuevo/composer.json)
            if [ -z "$VERSION" ]; then
              echo "No se pudo obtener la versión desde composer.json"
              exit 1
            fi
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "::set-output name=version::${VERSION}"
        shell: bash
