name: 4.2 CI/CD for Pull Requests to Main

on:
  pull_request:
    branches:
      - main
    types:
      - closed


jobs:

  ci_prod:
    name: Run CI Workflow for Dev
    uses: ./.github/workflows/ci.yml
    with:
      branch: main
      environment: production
    secrets: inherit
          
  cd_prod:
    name: Run CD Workflow for Prod
    needs: ci_prod
    uses: ./.github/workflows/cd-deploy-aks.yml
    with:
      version: ${{ needs.ci_prod.outputs.version }}
      repository: ${{ needs.ci_prod.outputs.repository }}
      environment: production
    secrets: inherit
          
  update_version:
    needs: cd_prod
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq


      - name: Recreating dev branch
        run: |
          
          git push origin --delete develop
          git checkout -b develop main
      
      - name: Display current version
        run: |
          echo "Current version:"
          jq -r .version aplicativo/aplicativoNuevo/composer.json

      - name: Update version in composer.json
        run: |
          version=$(jq -r .version aplicativo/aplicativoNuevo/composer.json)
          new_version=$(echo $version | awk -F. -v OFS=. '{$NF += 1 ; print}')
          sed -i "s/\"version\": \"$version\"/\"version\": \"$new_version\"/" aplicativo/aplicativoNuevo/composer.json
          
          echo "Updated version in composer.json:"
          jq -r .version aplicativo/aplicativoNuevo/composer.json
          
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.email "plopez@stemdo.io"
          git config --global user.name "ploopez"
            
          git add aplicativo/aplicativoNuevo/composer.json
          #if ! git diff --staged --quiet; then
            git commit -m "Updated version to $new_version"
            git push --set-upstream origin develop
          #else
            #echo "No changes to commit."
          #fi
