name: 4. Main Workflow CI/CD

on: 
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches: 
      - main
    paths:
      - 'aplicativo/aplicativoNuevo/**'
  push:
    branches:
      - develop

jobs:
  ci:
    name: Run CI Workflow
    uses: ./.github/workflows/ci.yml
    with:
      branch: ${{ github.ref == 'refs/heads/develop' && 'develop' || 'main' }}
    secrets: inherit

  download_artifacts_version:
    name: Download Version Artifact
    needs: ci
    runs-on: ubuntu-latest
    
    outputs:
      version: ${{ steps.read_version.outputs.version }}

    steps:
      - name: Download Version Artifact
        uses: actions/download-artifact@v3
        with:
          name: version
          path: ./version

      - name: List files in the directory
        run: ls -al ./version

      - name: Read Version from File
        id: read_version
        run: |
          VERSION=$(cat ./version/version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=version::$VERSION"

  print_version:
    name: Print Version from CI
    needs: [ci, download_artifacts_version]
    runs-on: ubuntu-latest

    steps:
      - name: Print Version from CI
        run: echo "La versión extraída es ${{ needs.download_artifacts_version.outputs.version }}"

  download_artifacts_repository:
    name: Download Repository Artifact
    needs: ci
    runs-on: ubuntu-latest
    
    outputs:
      repository: ${{ steps.read_repository.outputs.repository }}

    steps:
      - name: Download Repository Artifact
        uses: actions/download-artifact@v3
        with:
          name: repository
          path: ./repository

      - name: List files in the directory
        run: ls -al ./repository

      - name: Read Repository from File
        id: read_repository
        run: |
          REPOSITORY=$(cat ./repository/repository.txt)
          echo "REPOSITORY=$REPOSITORY" >> $GITHUB_ENV
          echo "::set-output name=repository::$REPOSITORY"

  print_version_repository:
    name: Print Repository Name
    needs: [ci, download_artifacts_repository]
    runs-on: ubuntu-latest

    steps:
      - name: Print Repository Name from CI
        run: echo "El nombre del repositorio es ${{ needs.download_artifacts_repository.outputs.repository }}"

  cd_job:
    name: Run CD Workflow
    needs: [ci, download_artifacts_version, download_artifacts_repository]
    uses: ./.github/workflows/cd-deploy-aks.yml
    with:
      version: ${{ needs.download_artifacts_version.outputs.version }}
      repository: ${{ needs.download_artifacts_repository.outputs.repository }}
    secrets: inherit
