name: 4.2 CI/CD for Pull Requests to Main

on:
  pull_request:
    branches:
      - main
    types:
      - closed


jobs:

  ci_prod:
    name: Run CI Workflow for Prod
    uses: ./.github/workflows/ci.yml
    with:
      branch: main
      environment: production
    secrets: inherit
          
  cd_prod:
    name: Run CD Workflow for Prod
    needs: ci_prod
    uses: ./.github/workflows/cd-deploy-aks.yml
    with:
      version: ${{ needs.ci_prod.outputs.version }}
      repository: ${{ needs.ci_prod.outputs.repository }}
      environment: production
    secrets: inherit
          
  update_version:
    needs: cd_prod
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Delete develop branch
        run: |
          run: git push origin --delete develop || true

      - name: Recreate develop branch from main
        run: |
          git fetch origin
          git checkout main
          git pull origin main
          git branch -D develop || true  
          git checkout -b develop
          git push origin develop
      
      - name: Checkout develop branch
        uses: actions/checkout@v4
        with:
          ref: develop
      
      - name: Display current version
        run: |
          echo "Current version:"
          jq -r .version aplicativo/aplicativoNuevo/composer.json

      - name: Update version in composer.json
        run: |
          version=$(jq -r .version aplicativo/aplicativoNuevo/composer.json)
          new_version=$(echo $version | awk -F. -v OFS=. '{$NF += 1 ; print}')
          echo "Updating version from $version to $new_version"
          sed -i "s/\"version\": \"$version\"/\"version\": \"$new_version\"/" aplicativo/aplicativoNuevo/composer.json
          
          echo "Updated version in composer.json:"
          jq -r .version aplicativo/aplicativoNuevo/composer.json
          
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.email "plopez@stemdo.io"
          git config --global user.name "ploopez"

          echo "Verifying changes in composer.json:"
          cat aplicativo/aplicativoNuevo/composer.json

          git add aplicativo/aplicativoNuevo/composer.json
          # el if git diff se utiliza para verificar si hay cambios en el stage, 
          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          else
            echo "Changes detected, committing..."
            git commit -m "Updated version to $new_version"
            git pull origin develop --rebase
            git push origin develop
          fi
