name: 4.2 CI/CD for Pull Requests to Main

on:
  pull_request:
    branches:
      - main
    types:
      - closed


jobs:
  ci_prod:
    name: Run CI Workflow for Dev
    uses: ./.github/workflows/ci.yml
    with:
      branch: main
      environment: production
    secrets: inherit
          
  cd_prod:
    name: Run CD Workflow for Prod
    needs: ci_prod
    uses: ./.github/workflows/cd-deploy-aks.yml
    with:
      version: ${{ needs.ci_prod.outputs.version }}
      repository: ${{ needs.ci_prod.outputs.repository }}
      environment: production
    secrets: inherit
          
  merge_and_delete_branch:
    name: Merge Develop to Main and Delete Develop
    needs: cd_prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: Merge develop into main
        run: |
          git fetch origin develop
          git checkout main
          git merge origin/develop --allow-unrelated-histories
          git push origin main  
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Delete develop branch
        run: |
          git push origin --delete develop
          git branch -d develop
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
  
  recreate_develop:
    name: Recreate Develop Branch from Main
    needs: merge_and_delete_branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create develop branch from main
        run: |
          git checkout main
          git checkout -b develop
          git push origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

  update_version:
    name: Update Version in Composer JSON
    needs: recreate_develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Update version in composer.json
        run: |
          current_version=${{ needs.ci_prod.outputs.version }}
          IFS='.' read -r major minor patch <<< "$current_version"
          next_minor=$((minor + 1))
          next_version="$major.$next_minor.$patch"
          jq --arg version "$next_version" '.version = $version' aplicativo/aplicativoNuevo/composer.json > aplicativo/aplicativoNuevo/composer.json.tmp
          mv aplicativo/aplicativoNuevo/composer.json.tmp aplicativo/aplicativoNuevo/composer.json

      - name: Commit and push changes
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git add aplicativo/aplicativoNuevo/composer.json
          git commit -m "Update version to $next_version"
          git push origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

  
