name: 4.2 CI/CD for Pull Requests to Main

on:
  pull_request:
    branches:
      - main
    types:
      - closed


jobs:

  ci_prod:
    name: Run CI Workflow for Dev
    uses: ./.github/workflows/ci.yml
    with:
      branch: main
      environment: production
    secrets: inherit
          
  cd_prod:
    name: Run CD Workflow for Prod
    needs: ci_prod
    uses: ./.github/workflows/cd-deploy-aks.yml
    with:
      version: ${{ needs.ci_prod.outputs.version }}
      repository: ${{ needs.ci_prod.outputs.repository }}
      environment: production
    secrets: inherit
           
  recreate_develop:
    name: Recreate Develop Branch from Main
    needs: cd_prod
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create develop branch from main
        run: |
          git push origin --delete develop
          git checkout -b develop main

  update_version:
    name: Update Version in Composer JSON
    needs: recreate_develop
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Update version in composer.json
        run: |
          git config --global user.email "plopez@stemdo.io"
          git config --global user.name "ploopez"
          current_version=${{ needs.ci_prod.outputs.version }}
          IFS='.' read -r major minor patch <<< "$current_version"
          next_minor=$((minor + 1))
          next_version="$major.$next_minor.$patch"
          jq --arg version "$next_version" '.version = $version' aplicativo/aplicativoNuevo/composer.json > aplicativo/aplicativoNuevo/composer.json.tmp
          mv aplicativo/aplicativoNuevo/composer.json.tmp aplicativo/aplicativoNuevo/composer.json
          git add aplicativo/aplicativoNuevo//composer.json
          git commit -m "New version to $next_version"
        
        
          

  
